server:  
  port: 9003
spring:  
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
  instance:
    prefer-ip-address: true #使用ip注册